In [20]:
import pandas as pd


In [21]:
df = pd. read_csv("C:/Users/windows 11/Downloads/Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [22]:
df["Species"] = df["Species"].replace("Iris-setosa", 0)
df["Species"] = df["Species"].replace("Iris-versicolor", 1)
df["Species"] = df["Species"].replace("Iris-virginica", 2)

print(df.tail())

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2


In [23]:
df.shape

(150, 6)

In [24]:
Y = df.values[:,5]
Y



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [25]:
X=df.values[:,1:5]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [27]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 100)
print(y_train.shape)
print(x_train.shape)

(112,)
(112, 4)


In [28]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import RMSprop
from tensorflow.keras.optimizers import Adam


In [29]:
first_layer_size = 32
num_classes=3
model = Sequential()
model.add(Dense(first_layer_size, activation='sigmoid', input_shape=(4,
                                                                     )))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 32)                160       
                                                                 
 dense_5 (Dense)             (None, 32)                1056      
                                                                 
 dense_6 (Dense)             (None, 32)                1056      
                                                                 
 dense_7 (Dense)             (None, 3)                 99        
                                                                 
Total params: 2371 (9.26 KB)
Trainable params: 2371 (9.26 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [30]:
print(y_test)
y_train = keras.utils.to_categorical(y_train, num_classes , dtype ="float")
y_test = keras.utils.to_categorical(y_test ,num_classes , dtype ="float")
y_test

[2. 0. 2. 0. 2. 2. 0. 0. 2. 0. 0. 2. 0. 0. 2. 1. 1. 1. 2. 2. 2. 0. 2. 0.
 1. 2. 1. 0. 1. 2. 1. 1. 2. 0. 0. 1. 0. 1.]


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [31]:
model.compile(loss= "categorical_crossentropy", 
             optimizer = RMSprop(),
             metrics= ['accuracy'])

In [32]:
import numpy as np 
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
history = model.fit(x_train , y_train,
                    batch_size = 10 ,
                    epochs = 100 ,
                    verbose = 1)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 1.1905 - accuracy: 0.3214
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 1.1114 - accuracy: 0.3214
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 1.1019 - accuracy: 0.3304
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 1.0952 - accuracy: 0.3750
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0953 - accuracy: 0.3571
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0900 - accuracy: 0.2946
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0865 - accuracy: 0.3661
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0822 - accuracy: 0.4196
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0768 - accuracy: 0.4018
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0728 - accuracy: 0.4554
Epoch 11/

12/12 [==============================] - 0s 2ms/step - loss: 0.1219 - accuracy: 0.9732
Epoch 84/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1182 - accuracy: 0.9643
Epoch 85/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1174 - accuracy: 0.9643
Epoch 86/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1192 - accuracy: 0.9554
Epoch 87/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1095 - accuracy: 0.9554
Epoch 88/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1030 - accuracy: 0.9643
Epoch 89/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1208 - accuracy: 0.9554
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1031 - accuracy: 0.9732
Epoch 91/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1124 - accuracy: 0.9643
Epoch 92/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1040 - accuracy: 0.9643
Epoch 93/100


In [34]:
model.compile(loss='mean_squared_error',
             optimizer='Adam',
             metrics=['accuracy'])

In [35]:
import numpy as np 
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
history = model.fit(x_train , y_train,
                    batch_size = 10 ,
                    epochs = 100 ,
                    verbose = 1)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 0.0174 - accuracy: 0.9643
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0214 - accuracy: 0.9464
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0143 - accuracy: 0.9732
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0171 - accuracy: 0.9643
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0148 - accuracy: 0.9732
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0152 - accuracy: 0.9732
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0148 - accuracy: 0.9732
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0198 - accuracy: 0.9554
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0155 - accuracy: 0.9464
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0150 - accuracy: 0.9732
Epoch 11/

12/12 [==============================] - 0s 3ms/step - loss: 0.0133 - accuracy: 0.9821
Epoch 84/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0144 - accuracy: 0.9643
Epoch 85/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0126 - accuracy: 0.9821
Epoch 86/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0129 - accuracy: 0.9821
Epoch 87/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0125 - accuracy: 0.9821
Epoch 88/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0126 - accuracy: 0.9732
Epoch 89/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0128 - accuracy: 0.9821
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0139 - accuracy: 0.9732
Epoch 91/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0158 - accuracy: 0.9643
Epoch 92/100
12/12 [==============================] - 0s 2ms/step - loss: 0.0121 - accuracy: 0.9821
Epoch 93/100


In [36]:
# write the testing input and output variable 
score = model.evaluate(x_test , y_test ,verbose=0)
print('Test loss: ' , score[0])
print('Test accuracy:',score[1])

Test loss:  0.004472655709832907
Test accuracy: 1.0


In [37]:
prediction = model.predict(x_test[1:25])
print(prediction)
print("prediction\n",(prediction>0.5).astype(int))
#pridiction_new = keras.utils.to_categorical(prediciton, num_classes , dype = 'float')
#print(prediction_new)


1/1 [==============================] - 0s 91ms/step
[[9.9629921e-01 3.6996941e-03 1.0929261e-06]
 [2.7283591e-09 2.9472848e-03 9.9705267e-01]
 [9.9728894e-01 2.7102348e-03 7.9895176e-07]
 [1.2408366e-06 1.7377552e-01 8.2622319e-01]
 [1.1639596e-08 8.1235487e-03 9.9187648e-01]
 [9.9731159e-01 2.6875704e-03 7.9228062e-07]
 [9.9609357e-01 3.9052174e-03 1.1522961e-06]
 [1.9280591e-07 5.3200386e-02 9.4679946e-01]
 [9.9573332e-01 4.2654355e-03 1.2600374e-06]
 [9.9679440e-01 3.2046274e-03 9.4520584e-07]
 [4.9059764e-08 2.1430355e-02 9.7856963e-01]
 [9.9582905e-01 4.1698059e-03 1.2327033e-06]
 [9.9676162e-01 3.2374666e-03 9.5415896e-07]
 [6.2062334e-08 2.5137411e-02 9.7486252e-01]
 [4.9332413e-04 9.9444550e-01 5.0612786e-03]
 [6.7194871e-04 9.9580055e-01 3.5275503e-03]
 [1.0652999e-05 5.6097734e-01 4.3901199e-01]
 [6.0297238e-09 5.1567890e-03 9.9484313e-01]
 [5.6500674e-08 2.3631344e-02 9.7636867e-01]
 [1.0115122e-07 3.4861747e-02 9.6513814e-01]
 [9.9624711e-01 3.7518616e-03 1.1068212e-06]
 [1

In [39]:
#check it worked right or not 
#print(x_test[23:25])
print(y_test[1:25])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
